# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "10fc70fda4d73a96685054e809c9f643"
name = "front-connect"
handle = "front-connect-2"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "custom-sample-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
